//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boozic
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductFlag
    {
        public int Id { get; set; }
        public string DeviceId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> Reason { get; set; }
        public Nullable<System.DateTime> FlaggedOn { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
