//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boozic
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypesDetail
    {
        public TypesDetail()
        {
            this.Products1 = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        public int ParentId { get; set; }
        public string Description { get; set; }
    
        public virtual Type Type { get; set; }
        public virtual ICollection<Product> Products1 { get; set; }
    }
}
